/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vino_VinoNativeRender */

#ifndef _Included_com_example_vino_VinoNativeRender
#define _Included_com_example_vino_VinoNativeRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    setGlobe
 * Signature: ([Lcom/example/vino/ViewResolution;Lcom/example/vino/ViewPerspective;Lcom/example/vino/stdCamPos;I)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_setGlobe
  (JNIEnv *, jclass, jobjectArray, jobject, jobject, jint);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    setData
 * Signature: (Lcom/example/vino/DataPacket;)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_setData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onUpdate
 * Signature: (Lcom/example/vino/MotionData;)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onUpdate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onProcess
  (JNIEnv *, jclass);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    onDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_onDestory
  (JNIEnv *, jclass);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    SetCamera
 * Signature: (Lcom/example/vino/stdCamPos;)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_SetCamera
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_vino_VinoNativeRender
 * Method:    getCamera
 * Signature: (Lcom/example/vino/stdCamPos;)V
 */
JNIEXPORT void JNICALL Java_com_example_vino_VinoNativeRender_getCamera
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
